Vagrant.configure("2") do |config|
  
  config.vm.boot_timeout = 1000

  config.vm.box = "peru/ubuntu-18.04-server-amd64"
  config.vm.network "private_network", ip: "193.168.183.158"
  config.vm.network "forwarded_port", guest: 27017, host: 27018,  host_id: "127.0.0.1", guest_ip: "193.168.183.158"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "d-play-vm"
    vb.memory = "2048"
    vb.gui = false
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt update
    apt -y install aptitude

    aptitude -y install mongodb

    curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -

    systemctl start mongodb.service
    sed -i 's/bind_ip = 127.0.0.1/bind_ip = 127.0.0.1,193.168.183.158/' /etc/mongodb.conf
    
    ifconfig eth1 193.168.183.158 netmask 255.255.255.0 up
  SHELL

  config.vm.provision "shell", run: "always", inline: <<-SHELL
    systemctl restart mongodb.service
  SHELL
end
